events {}

http {

    resolver 8.8.8.8 ipv6=off;

    log_format simple '$remote_addr $host "$request" $status';
    access_log /var/log/nginx/access.log simple;

    server {
        listen 80;
        server_name inspire.ec.europa.eu;

        location / {

            set $backend inspire.ec.europa.eu;

            proxy_pass https://$backend;

            proxy_ssl_server_name on;

            proxy_set_header Host inspire.ec.europa.eu;

            proxy_intercept_errors on;
            error_page 301 302 307 = @handle_redirect;
        }

        location @handle_redirect {
            set $redirect_url $upstream_http_location;
            proxy_pass $redirect_url;
        }
    }
}