events {}

http {

    server {
        listen 80;
        listen 443 ssl;

        server_name inspire.ec.europa.eu;

        ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
        ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;

        location / {
            proxy_pass https://inspire.ec.europa.eu;
            proxy_ssl_server_name on;
            proxy_set_header Host inspire.ec.europa.eu;
        }
    }

}