acl localnet src all
http_access allow localnet
http_port 3128

# FORCE HIGH MEMORY USAGE
fqdncache_size 100000
ipcache_size 100000
memory_pools on
memory_pools_limit 1500 MB
dns_children 128 startup=64 idle=32

cache_mem 512 MB
maximum_object_size_in_memory 512 KB