# Generated by Django 5.2.17 on 2026-09-21 16:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='S3Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200)),
                ('credential_ref', models.CharField(blank=True, editable=False, help_text='Reference to private S3 credentials outside the database; blank for imported history.', max_length=32)),
                ('bucketname', models.CharField(max_length=100)),
                ('key_prefix', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'storage_delivery_source',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('size_bytes', models.BigIntegerField()),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('product_ident', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('product_description', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('product_unit_code', models.CharField(blank=True, default=None, editable=False, help_text='Canonical product unit code projected from the latest delivery job.', max_length=255, null=True)),
                ('verified_product_unit_code', models.CharField(blank=True, default=None, editable=False, help_text='Canonical product unit code verified from this input ZIP and retained across later jobs. ProductUnit.product_unit_code is the authoritative expected value.', max_length=255, null=True)),
                ('content_sha256', models.CharField(blank=True, default=None, editable=False, max_length=64, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('s3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.s3info')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'db_table': 'execution_delivery',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('readiness_revision', models.PositiveIntegerField(default=0, editable=False)),
                ('ready_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ready_by_username', models.CharField(blank=True, editable=False, max_length=150)),
                ('ready_scope_digest', models.CharField(blank=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ready_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_product',
                'ordering': ('ident',),
            },
        ),
        migrations.CreateModel(
            name='ProductRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_key', models.CharField(max_length=100)),
                ('revision', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('catalog_digest', models.CharField(max_length=64)),
                ('source_kind', models.CharField(choices=[('definition', 'Definition directory'), ('manifest', 'Release manifest'), ('upload', 'Specification upload')], default='manifest', max_length=20)),
                ('coverage_state', models.CharField(choices=[('unknown', 'Coverage unknown'), ('draft', 'Draft coverage'), ('authoritative', 'Authoritative coverage'), ('retired', 'Retired')], default='unknown', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_product_releases', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='dashboard.product')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='dashboard.productrelease')),
            ],
            options={
                'db_table': 'catalog_release_revision',
                'ordering': ('release_key', '-revision'),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('job_status', models.CharField(default='waiting', max_length=64)),
                ('product_ident', models.CharField(max_length=64)),
                ('product_description', models.CharField(max_length=500)),
                ('product_unit_code', models.CharField(blank=True, default=None, editable=False, help_text='Canonical product unit code reported by the delivery job result.', max_length=255, null=True)),
                ('verified_product_unit_code', models.CharField(blank=True, default=None, editable=False, help_text="Canonical product unit code verified from this job's input ZIP; not a review decision.", max_length=255, null=True)),
                ('skip_steps', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('worker_url', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('requested_by_username', models.CharField(blank=True, max_length=150)),
                ('request_source', models.CharField(blank=True, choices=[('browser', 'Browser'), ('api', 'API')], default=None, help_text='Request channel when known; NULL means the channel was not recorded.', max_length=16, null=True)),
                ('requested_api_token_id', models.PositiveBigIntegerField(blank=True, editable=False, help_text='Identifier snapshot of the personal API token used to request the job. It intentionally has no foreign key so deleting a credential cannot rewrite audit history.', null=True)),
                ('requested_api_token_name', models.CharField(blank=True, max_length=80)),
                ('input_sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('reference_period', models.CharField(blank=True, editable=False, max_length=32)),
                ('delivery', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.delivery')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_qc_jobs', to=settings.AUTH_USER_MODEL)),
                ('product_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='dashboard.productrelease')),
            ],
            options={
                'db_table': 'execution_job',
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_unit_code', models.CharField(max_length=255)),
                ('source_value', models.CharField(blank=True, max_length=255)),
                ('provenance', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_release', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='product_units', to='dashboard.productrelease')),
            ],
            options={
                'db_table': 'catalog_product_unit',
                'ordering': ('product_release_id', 'product_unit_code'),
            },
        ),
        migrations.CreateModel(
            name='DeliverySubmission',
            fields=[
                ('submission_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_unit_code', models.CharField(editable=False, max_length=255)),
                ('verified_product_unit_code', models.CharField(editable=False, max_length=255)),
                ('submitted_by_username', models.CharField(max_length=150)),
                ('request_channel', models.CharField(choices=[('browser', 'Browser'), ('api', 'API')], max_length=10)),
                ('api_token_id', models.PositiveBigIntegerField(blank=True, editable=False, help_text='Identifier snapshot of the API token used for submission. It is deliberately not a foreign key because credentials may be deleted while submission provenance must remain immutable.', null=True)),
                ('api_token_name', models.CharField(blank=True, max_length=80)),
                ('publication_state', models.CharField(choices=[('pending', 'Pending'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('review_state', models.CharField(choices=[('pending', 'Awaiting review'), ('accepted', 'Approved'), ('conflict', 'Competing submissions'), ('rejected', 'Declined')], default='pending', max_length=10)),
                ('review_version', models.PositiveIntegerField(default=0, editable=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('publication_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('publication_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('artifact_key', models.CharField(blank=True, help_text='Immutable directory key relative to the configured submission storage root.', max_length=1000)),
                ('artifact_digest', models.CharField(blank=True, max_length=64)),
                ('input_digest', models.CharField(blank=True, max_length=64)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.CharField(blank=True, max_length=500)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='dashboard.delivery')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_submissions', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='dashboard.job')),
                ('product_release', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='dashboard.productrelease')),
                ('product_unit', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='dashboard.productunit')),
            ],
            options={
                'db_table': 'publication_submission',
                'ordering': ('-requested_at', 'submission_uuid'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='QcDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ident', models.CharField(max_length=64)),
                ('digest', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('document', models.JSONField()),
                ('source_path', models.CharField(max_length=500)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'catalog_definition_revision',
                'ordering': ('product_ident', '-imported_at', '-pk'),
                'indexes': [models.Index(fields=['product_ident', '-imported_at'], name='catalog_def_ident_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('product_ident', ''), _negated=True), name='catalog_def_ident_present'), models.CheckConstraint(condition=models.Q(('digest', ''), _negated=True), name='catalog_def_digest_present'), models.UniqueConstraint(fields=('product_ident', 'digest'), name='catalog_def_ident_digest_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ProductReleaseDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('product_release', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='definition_links', to='dashboard.productrelease')),
                ('qc_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_links', to='dashboard.qcdefinition')),
            ],
            options={
                'db_table': 'catalog_release_definition',
                'ordering': ('product_release_id', '-is_primary', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='job',
            name='qc_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='dashboard.qcdefinition'),
        ),
        migrations.CreateModel(
            name='SubmissionConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Closed')], default='open', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('opened_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_username', models.CharField(blank=True, max_length=150)),
                ('resolution_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='submission_conflict', to='dashboard.productunit')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_submission_conflicts', to=settings.AUTH_USER_MODEL)),
                ('selected_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_for_conflicts', to='dashboard.deliverysubmission')),
            ],
            options={
                'db_table': 'publication_conflict',
                'ordering': ('state', '-opened_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SubmissionConflictEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('opened', 'Opened'), ('reopened', 'Reopened'), ('resolved', 'Resolved'), ('dismissed', 'Closed'), ('candidate', 'Candidate added')], max_length=10)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_conflict_events', to=settings.AUTH_USER_MODEL)),
                ('conflict', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='dashboard.submissionconflict')),
                ('selected_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conflict_events', to='dashboard.deliverysubmission')),
            ],
            options={
                'db_table': 'publication_conflict_event',
                'ordering': ('conflict_id', 'version', 'created_at', 'pk'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='SubmissionReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined')], max_length=10)),
                ('actor_username', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_review_events', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='review_events', to='dashboard.deliverysubmission')),
            ],
            options={
                'db_table': 'publication_review_event',
                'ordering': ('created_at', 'pk'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('ident', ''), _negated=True), name='catalog_product_ident_present'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='catalog_product_name_present'),
        ),
        migrations.AddIndex(
            model_name='productrelease',
            index=models.Index(fields=['product', 'coverage_state', 'is_current'], name='catalog_release_coverage_idx'),
        ),
        migrations.AddConstraint(
            model_name='productrelease',
            constraint=models.CheckConstraint(condition=models.Q(('coverage_state__in', ('unknown', 'draft', 'authoritative', 'retired'))), name='catalog_release_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='productrelease',
            constraint=models.CheckConstraint(condition=models.Q(('source_kind__in', ('definition', 'manifest', 'upload'))), name='catalog_release_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='productrelease',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('coverage_state', 'authoritative'), _negated=True), ('approved_at__isnull', False), _connector='OR'), name='catalog_release_approved'),
        ),
        migrations.AddConstraint(
            model_name='productrelease',
            constraint=models.CheckConstraint(condition=models.Q(('release_key', ''), _negated=True), name='catalog_release_key_present'),
        ),
        migrations.AddConstraint(
            model_name='productrelease',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gt', 0)), name='catalog_release_revision_gt0'),
        ),
        migrations.AddConstraint(
            model_name='productrelease',
            constraint=models.CheckConstraint(condition=models.Q(('catalog_digest', ''), _negated=True), name='catalog_release_digest_present'),
        ),
        migrations.AddConstraint(
            model_name='productrelease',
            constraint=models.UniqueConstraint(fields=('release_key', 'revision'), name='catalog_release_revision_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productrelease',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('release_key',), name='catalog_release_current_uniq'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['product_unit_code', 'product_release'], name='catalog_unit_code_release_idx'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.CheckConstraint(condition=models.Q(('product_unit_code', ''), _negated=True), name='catalog_product_unit_code_present'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(fields=('product_release', 'product_unit_code'), name='catalog_product_unit_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='deliverysubmission',
            index=models.Index(fields=['product_unit', 'publication_state', 'review_state'], name='pub_submission_unit_state_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverysubmission',
            index=models.Index(fields=['product_release', 'publication_state'], name='pub_submission_release_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverysubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('publication_state', 'published'), ('review_state', 'accepted')), fields=('product_unit',), name='pub_unit_accepted_uniq'),
        ),
        migrations.AddConstraint(
            model_name='deliverysubmission',
            constraint=models.CheckConstraint(condition=models.Q(('publication_state__in', ('pending', 'publishing', 'published', 'failed'))), name='pub_submission_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='deliverysubmission',
            constraint=models.CheckConstraint(condition=models.Q(('review_state__in', ('pending', 'accepted', 'conflict', 'rejected'))), name='pub_submission_review_valid'),
        ),
        migrations.AddConstraint(
            model_name='deliverysubmission',
            constraint=models.CheckConstraint(condition=models.Q(('request_channel__in', ('browser', 'api'))), name='pub_submission_channel_valid'),
        ),
        migrations.AddConstraint(
            model_name='deliverysubmission',
            constraint=models.CheckConstraint(condition=models.Q(('product_unit_code', ''), _negated=True), name='pub_submission_unit_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='deliverysubmission',
            constraint=models.CheckConstraint(condition=models.Q(('verified_product_unit_code', ''), _negated=True), name='pub_submission_zip_unit_present'),
        ),
        migrations.AddConstraint(
            model_name='deliverysubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_state', 'published'), _negated=True), models.Q(('published_at__isnull', False), models.Q(('artifact_key', ''), _negated=True), models.Q(('artifact_digest', ''), _negated=True), models.Q(('input_digest', ''), _negated=True)), _connector='OR'), name='pub_submission_complete'),
        ),
        migrations.AddConstraint(
            model_name='productreleasedefinition',
            constraint=models.UniqueConstraint(fields=('product_release', 'qc_definition'), name='catalog_release_def_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productreleasedefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product_release',), name='catalog_release_primary_uniq'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['product_unit_code'], name='execution_job_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['verified_product_unit_code'], name='execution_job_zip_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['delivery', '-date_created', '-job_uuid'], name='execution_job_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_status', 'date_created'], name='execution_job_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('request_source__isnull', True), ('request_source__in', ('browser', 'api')), _connector='OR'), name='execution_job_source_valid'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['product_unit_code'], name='execution_delivery_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['verified_product_unit_code'], name='execution_delivery_zipunit_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['content_sha256'], name='execution_delivery_sha_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='execution_delivery_size_valid'),
        ),
        migrations.AddConstraint(
            model_name='submissionconflict',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='pub_conflict_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='submissionconflict',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('selected_submission__isnull', True), ('state', 'open')), models.Q(('resolved_at__isnull', False), ('selected_submission__isnull', False), ('state', 'resolved')), models.Q(('resolved_at__isnull', False), ('selected_submission__isnull', True), ('state', 'dismissed')), _connector='OR'), name='pub_conflict_state_consistent'),
        ),
        migrations.AddConstraint(
            model_name='submissionconflictevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('opened', 'reopened', 'resolved', 'dismissed', 'candidate'))), name='pub_conflict_event_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='submissionconflictevent',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='pub_conflict_event_version_gt0'),
        ),
        migrations.AddConstraint(
            model_name='submissionconflictevent',
            constraint=models.UniqueConstraint(fields=('conflict', 'version', 'event_type'), name='pub_conflict_event_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='submissionreviewevent',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ('approved', 'declined'))), name='pub_review_decision_valid'),
        ),
        migrations.AddConstraint(
            model_name='submissionreviewevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'declined'), _negated=True), models.Q(('notes', ''), _negated=True), _connector='OR'), name='pub_review_decline_reason'),
        ),
        migrations.AddConstraint(
            model_name='submissionreviewevent',
            constraint=models.UniqueConstraint(fields=('submission', 'version'), name='pub_review_event_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='submissionreviewevent',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='pub_review_version_positive'),
        ),
    ]
