# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-12 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('layer', models.CharField(blank=True, max_length=200)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=200)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('log_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(max_length=500)),
                ('storage', models.CharField(max_length=500)),
                ('version', models.CharField(max_length=50)),
                ('layers', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('extension', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('file_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.FileFormat')),
            ],
        ),
        migrations.AddField(
            model_name='checkingsession',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.File'),
        ),
        migrations.AddField(
            model_name='checkingsession',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Product'),
        ),
        migrations.AddField(
            model_name='checkingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
