version: '3'

services:
  qc_tool_frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: qc_tool_frontend
    ports:
      - 8000:8000
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_boundary/boundaries
      - INCOMING_DIR=/mnt/qc_tool_incoming/incoming
      - WPS_DIR=/mnt/qc_tool_wps
      - WORK_DIR=/mnt/qc_tool_work
      - FRONTEND_PORT=8000
      - FRONTEND_DB_PATH=/mnt/qc_tool_work/frontend.sqlite3
      - WPS_URL=http://qc_tool_wps:5000/wps
      - SHOW_LOGO=no
    networks:
      - qc_tool_network
    volumes:
      - /home/jiri/qc_tool/qc_tool_boundary:/mnt/qc_tool_boundary
      - /home/jiri/qc_tool/qc_tool_incoming:/mnt/qc_tool_incoming/incoming
      - /home/jiri/qc_tool/qc_tool_wps:/mnt/qc_tool_wps
      - /home/jiri/qc_tool/qc_tool_work:/mnt/qc_tool_work
      - /home/jiri/qc_tool/qc_tool_submission:/mnt/qc_tool_submission
      - /home/jiri/github/copernicus_quality_tools:/usr/local/src/copernicus_quality_tools

  qc_tool_wps:
    build:
      context: .
      dockerfile: Dockerfile.wps
    image: qc_tool_wps
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_boundary/boundaries
      - INCOMING_DIR=/mnt/qc_tool_incoming/incoming
      - WPS_DIR=/mnt/qc_tool_wps
      - WORK_DIR=/mnt/qc_tool_work
      - WPS_PARALLEL_PROCESSES=32
      - WPS_QUEUE_LENGTH=32
      - WPS_DBLOG_URL=sqlite:////var/dblog.sqlite3
      - PG_HOST=qc_tool_postgis
      - PG_PORT=5432
      - PG_USER=qc_job
      - PG_DATABASE=qc_tool_db
      - LEAVE_SCHEMA=no
      - JOBDIR_EXIST_OK=no
      - LEAVE_JOBDIR=no
      - SHOW_LOGO=no
    networks:
      - qc_tool_network
    volumes:
      - /home/jiri/qc_tool/qc_tool_boundary:/mnt/qc_tool_boundary
      - /home/jiri/qc_tool/qc_tool_incoming:/mnt/qc_tool_incoming/incoming
      - /home/jiri/qc_tool/qc_tool_wps:/mnt/qc_tool_wps
      - /home/jiri/qc_tool/qc_tool_work:/mnt/qc_tool_work
      - /home/jiri/github/copernicus_quality_tools:/usr/local/src/copernicus_quality_tools

  qc_tool_postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    image: qc_tool_postgis
    networks:
      - qc_tool_network

networks:
  qc_tool_network:
    driver: bridge
