FROM ubuntu:focal

LABEL author=gisat.cz
LABEL description="QC tool environment, running tests."

ARG VERSION

ENV PYTHONPATH=/usr/local/src/copernicus_quality_tools/src
ENV VERSION=${VERSION:-${DOCKER_TAG:-master}}

# Build the initial environment.
RUN echo "$VERSION" >/etc/qc_tool_version.txt \
    && apt-get -y update \
    && apt-get -y upgrade \
    && apt-get -y install wget unzip time gnupg2

# Install python and bootstrap pip.
RUN cd /usr/local/src \
    && apt-get -y install python3 python3-distutils \
    && wget --no-verbose https://bootstrap.pypa.io/get-pip.py \
    && python3 get-pip.py

# Install environment.
RUN apt-get -y install gdal-bin python3-gdal \
    && apt-get -y install python3-psycopg2 \
    && pip3 install numpy \
    && pip3 install boto3 \
    && pip3 install scikit-image \
    && pip3 install reportlab==3.6.13 \
    && pip3 install bottle \
    && pip3 install supervisor

RUN pip3 install requests

# Install qc tool.
RUN cd /usr/local/src && mkdir ./copernicus_quality_tools
#RUN cd /usr/local/src \
#    && wget --no-verbose https://github.com/eea/copernicus_quality_tools/archive/${VERSION}.zip \
#    && unzip -q ./${VERSION}.zip \
#    && rm ./${VERSION}.zip \
#    && mv ./copernicus_quality_tools-${VERSION} ./copernicus_quality_tools \
#    && echo ${VERSION} >./copernicus_quality_tools/VERSION
