version: '3'

services:
  qc_tool_frontend:
    depends_on:
      - qc_tool_wps
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: qc_tool_frontend
    ports:
      - 8000:8000
    environment:
      - INCOMING_DIR=/mnt/qc_tool_volume/incoming
      - WPS_DIR=/mnt/qc_tool_volume/wps
      - WORK_DIR=/mnt/qc_tool_volume/work
      - FRONTEND_PORT=8000
      - FRONTEND_DB_PATH=/var/lib/qc_tool/frontend.sqlite3
      - WPS_URL=http://qc_tool_wps:5000/wps
    networks:
      - qc_tool_network
    volumes:
      - qc_tool_volume:/mnt/qc_tool_volume
      - qc_tool_frontend:/var/lib/qc_tool
      - ../../copernicus_quality_tools:/usr/local/src/copernicus_quality_tools

  qc_tool_wps:
    depends_on:
      - qc_tool_postgis
    build:
      context: .
      dockerfile: Dockerfile.wps
    image: qc_tool_wps
    environment:
      - INCOMING_DIR=/mnt/qc_tool_volume/incoming
      - WPS_DIR=/mnt/qc_tool_volume/wps
      - WORK_DIR=/mnt/qc_tool_volume/work
      - WPS_PORT=5000
      - WPS_URL=http://qc_tool_wps:5000/wps
      - WPS_OUTPUT_URL=http://qc_tool_wps:5000/output
      - PG_HOST=qc_tool_postgis
      - PG_PORT=5432
      - PG_USER=qc_job
      - PG_DATABASE=qc_tool_db
      - LEAVE_SCHEMA=no
      - JOBDIR_EXIST_OK=no
      - LEAVE_JOBDIR=no
    networks:
      - qc_tool_network
    volumes:
      - qc_tool_volume:/mnt/qc_tool_volume
      - ../../copernicus_quality_tools:/usr/local/src/copernicus_quality_tools

  qc_tool_postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    image: qc_tool_postgis
    networks:
      - qc_tool_network

volumes:
  qc_tool_frontend:
    driver: local
  qc_tool_volume:
    driver: local

networks:
  qc_tool_network:
    driver: bridge