version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VERSION=1.2.9

    image: eeacms/copernicus-qctool-frontend:latest
    ports:
      - 8000:8000
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_boundary/boundaries
      - INCOMING_DIR=/mnt/qc_tool_incoming/incoming
      - WORK_DIR=/mnt/qc_tool_work
      - SUBMISSION_DIR=/mnt/qc_tool_submission/submission
      - FRONTEND_PORT=8000
      - FRONTEND_DB_PATH=/mnt/qc_tool_work/frontend.sqlite3
      - SHOW_LOGO=yes
    networks:
      - qc_tool_network
    volumes:
      - /home/jiri/qc_tool/qc_tool_boundary:/mnt/qc_tool_boundary
      - /home/jiri/qc_tool/qc_tool_incoming:/mnt/qc_tool_incoming/incoming
      - /home/jiri/qc_tool/qc_tool_work:/mnt/qc_tool_work
      - /home/jiri/qc_tool/qc_tool_submission:/mnt/qc_tool_submission
      - /home/jiri/github/copernicus_quality_tools:/usr/local/src/copernicus_quality_tools

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
      args:
        - VERSION=1.2.9

    image: eeacms/copernicus-qctool-worker:latest
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_boundary/boundaries
      - INCOMING_DIR=/mnt/qc_tool_incoming/incoming
      - PULL_JOB_URL=http://frontend:8000/pull_job
      - WORK_DIR=/mnt/qc_tool_work
      - PG_HOST=postgis
      - PG_PORT=5432
      - PG_USER=qc_job
      - PG_DATABASE=qc_tool_db
      - LEAVE_SCHEMA=no
      - LEAVE_JOBDIR=no
      - SHOW_LOGO=no
    networks:
      - qc_tool_network
    volumes:
      - /home/jiri/qc_tool/qc_tool_boundary:/mnt/qc_tool_boundary
      - /home/jiri/qc_tool/qc_tool_incoming:/mnt/qc_tool_incoming/incoming
      - /home/jiri/qc_tool/qc_tool_work:/mnt/qc_tool_work
      - /home/jiri/github/copernicus_quality_tools:/usr/local/src/copernicus_quality_tools

  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
      args:
        - VERSION=1.2.9
    image: eeacms/copernicus-qctool-postgis:latest
    networks:
      - qc_tool_network

networks:
  qc_tool_network:
    driver: bridge
