version: '3'
services:
  qc_tool_wps:
    depends_on:
      - qc_tool_postgis
    build:
      context: .
      dockerfile: Dockerfile.wps
    environment:
      - INCOMING_DIR
      - WPS_DIR
      - WORK_DIR
      - WPS_HOST
      - WPS_PORT
      - WPS_URL
      - WPS_OUTPUT_URL
      - PG_HOST
      - PG_PORT
      - PG_USER
      - PG_DATABASE
      - LEAVE_SCHEMA
      - JOBDIR_EXIST_OK
      - LEAVE_JOBDIR
    volumes:
      - "${WPS_MOUNT}:${WPS_DIR}"
  qc_tool_frontend:
    depends_on:
      - qc_tool_wps
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - INCOMING_DIR
      - WPS_URL
    volumes:
      - "${WPS_MOUNT}:${WPS_DIR}"
  qc_tool_postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis