version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: qc_tool_frontend
    ports:
      - 8000:8000
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_boundary/boundaries
      - INCOMING_DIR=/mnt/qc_tool_volume/incoming
      - WORK_DIR=/mnt/qc_tool_volume/work
      - SUBMISSION_DIR=/mnt/qc_tool_volume/submission
      - FRONTEND_PORT=8000
      - FRONTEND_DB_PATH=/var/lib/qc_tool/frontend.sqlite3
    networks:
      - qc_tool_network
    volumes:
      - qc_tool_boundary:/mnt/qc_tool_boundary
      - qc_tool_volume:/mnt/qc_tool_volume
      - qc_tool_frontend:/var/lib/qc_tool
      - ../../copernicus_quality_tools:/usr/local/src/copernicus_quality_tools

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: qc_tool_worker
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_boundary/boundaries
      - INCOMING_DIR=/mnt/qc_tool_volume/incoming
      - PULL_JOB_URL=http://frontend:8000/pull_job
      - WORK_DIR=/mnt/qc_tool_volume/work
      - PG_HOST=postgis
      - PG_PORT=5432
      - PG_USER=qc_job
      - PG_DATABASE=qc_tool_db
      - LEAVE_SCHEMA=no
      - JOBDIR_EXIST_OK=no
      - LEAVE_JOBDIR=no
    networks:
      - qc_tool_network
    volumes:
      - qc_tool_boundary:/mnt/qc_tool_boundary
      - qc_tool_volume:/mnt/qc_tool_volume
      - ../../copernicus_quality_tools:/usr/local/src/copernicus_quality_tools

  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    image: qc_tool_postgis
    networks:
      - qc_tool_network

volumes:
  qc_tool_boundary:
    driver: local
  qc_tool_frontend:
    driver: local
  qc_tool_volume:
    driver: local

networks:
  qc_tool_network:
    driver: bridge