version: '3'
services:
  qc_tool_wps:
    depends_on:
      - qc_tool_postgis
    build:
      context: .
      dockerfile: Dockerfile.wps
    environment:
      - PG_HOST
      - PG_DATABASE_NAME
      - WPS_DIR
      - WPS_PORT
      - WPS_URL
      - WPS_OUTPUT_URL
      - INCOMING_DIR
    volumes:
      - "${WPS_MOUNT}:${WPS_DIR}"
  qc_tool_frontend:
    depends_on:
      - qc_tool_wps
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - FRONTEND_PORT
      - WPS_URL
      - INCOMING_DIR
    volumes:
      - "${WPS_MOUNT}:${WPS_DIR}"
  qc_tool_postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis