version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: qc_tool_frontend
    ports:
      - 8000:8000
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_boundary/boundaries
      - INCOMING_DIR=/mnt/qc_tool_incoming/incoming
      - WORK_DIR=/mnt/qc_tool_work/work
      - SUBMISSION_DIR=/mnt/qc_tool_work/submission
      - FRONTEND_PORT=8000
      - FRONTEND_DB_PATH=/var/lib/qc_tool/frontend.sqlite3
    networks:
      - qc_tool_network
    volumes:
      - /mnt/pracovni-archiv-01/projects/cop15m/boundaries:/mnt/qc_tool_boundary/boundaries
      - /mnt/pracovni-archiv-01/projects/cop15m/incoming:/mnt/qc_tool_incoming/incoming
      - /mnt/pracovni-archiv-01/projects/cop15m/igor/qc_tool_work:/mnt/qc_tool_work
      - /mnt/pracovni-archiv-01/projects/cop15m/igor/copernicus_quality_tools:/usr/local/src/copernicus_quality_tools

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: qc_tool_worker
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_boundary/boundaries
      - INCOMING_DIR=/mnt/qc_tool_incoming/incoming
      - PULL_JOB_URL=http://frontend:8000/pull_job
      - WORK_DIR=/mnt/qc_tool_work/work
      - PG_HOST=postgis
      - PG_PORT=5432
      - PG_USER=qc_job
      - PG_DATABASE=qc_tool_db
      - LEAVE_SCHEMA=no
      - LEAVE_JOBDIR=no
    networks:
      - qc_tool_network
    volumes:
      - /mnt/pracovni-archiv-01/projects/cop15m/boundaries:/mnt/qc_tool_boundary/boundaries
      - /mnt/pracovni-archiv-01/projects/cop15m/incoming:/mnt/qc_tool_incoming/incoming
      - /mnt/pracovni-archiv-01/projects/cop15m/igor/qc_tool_work:/mnt/qc_tool_work
      - /mnt/pracovni-archiv-01/projects/cop15m/igor/copernicus_quality_tools:/usr/local/src/copernicus_quality_tools

  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    image: qc_tool_postgis
    networks:
      - qc_tool_network

networks:
  qc_tool_network:
    driver: bridge
