apiVersion: v1
kind: Pod
metadata:
  name: qc-worker-repro
spec:
  containers:
    - name: worker
      image: eeacms/copernicus-qctool-worker:2.3.6rc5
      resources:
        limits:
          memory: "2Gi"  # This is the "Wall" SQuID will hit
      env:
        - name: JAVA_MAX_MEM
          value: "1500"
        - name: RUN_INSPIRE_VALIDATOR
          value: "no"
        - name: PULL_JOB_URL
          value: "http://localhost:8000/pull_job"
        - name: INSPIRE_SERVICE_URL
          value: "http://localhost:8080/validator/v2/"
