apiVersion: v1
kind: Pod
metadata:
  name: qc-worker-repro
spec:
  containers:
    - name: worker
      image: eeacms/copernicus-qctool-worker:2.3.5
      resources:
        limits:
          memory: "2Gi"
      volumeMounts:
        - name: squid-config
          mountPath: /etc/squid/squid.conf
          subPath: squid.conf
  volumes:
    - name: squid-config
      configMap:
        name: squid-stress-config