; Supervisor config file for qc_tool worker container.

[unix_http_server]
file=/run/supervisor.sock

[inet_http_server]
port=*:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/run/supervisord.pid
nodaemon=true
directory=/tmp
nocleanup=true
user=root

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[program:postgresql]
command=/usr/local/bin/start_optional_postgres.sh Postgres /usr/lib/postgresql/17/bin/postgres -D /var/lib/postgresql/17/main -c config_file=/etc/postgresql/17/main/postgresql.conf
user=postgres
numprocs=1
autostart=true
startsecs=2
startretries=0
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:scheduler]
command=python3 -m qc_tool.worker.scheduler
numprocs=1
autostart=true
startsecs=2
startretries=0
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/local/bin/start_optional_service.sh Nginx /usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx/stdout.log
stderr_logfile=/var/log/nginx/stderr.log

[program:inspirevalidator]
; Prefix the command with the wrapper
command=/usr/local/bin/start_optional_service.sh Validator java -Djava.io.tmpdir=/tmp/jetty -server -Xms512m -Xmx2g -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044 -jar /usr/local/jetty/start.jar
directory=/usr/local/jetty
autostart=true
startsecs=20
startretries=5
autorestart=true
stderr_logfile=/var/log/inspire_validator.err.log
stdout_logfile=/var/log/inspire_validator.out.log

[eventlistener:watcher]
events=PROCESS_STATE_STOPPED, PROCESS_STATE_EXITED, PROCESS_STATE_FATAL
command=bash -c 'echo READY; read line; echo watcher: killing supervisord >&2; kill -SIGTERM $PPID'
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startretries=0
autorestart=false
