# Generated by Django 2.0.4 on 2018-04-25 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('layer', models.CharField(blank=True, max_length=200)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=200)),
                ('percent_complete', models.CharField(blank=True, max_length=50, null=True)),
                ('wps_request', models.CharField(blank=True, max_length=400, null=True)),
                ('wps_status_location', models.CharField(max_length=400, null=True)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('log_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(max_length=500)),
                ('storage', models.CharField(max_length=500)),
                ('version', models.CharField(max_length=50)),
                ('layers', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('extension', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('file_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.FileFormat')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.FileFormat'),
        ),
        migrations.AddField(
            model_name='checkingsession',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.File'),
        ),
        migrations.AddField(
            model_name='checkingsession',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Product'),
        ),
        migrations.AddField(
            model_name='checkingsession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
