# Generated by Django 2.0.4 on 2018-07-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='last_job_percent',
            field=models.IntegerField(null=True),
        ),
    ]
