# Generated by Django 2.0.4 on 2018-10-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delivery_last_job_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='product_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='size_bytes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='size_bytes2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='delivery',
            table='deliverys2',
        ),
    ]
