# Generated by Django 2.0.4 on 2018-04-17 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180412_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkingsession',
            name='wps_request',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkingsession',
            name='wps_status_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.FileFormat'),
        ),
    ]
