# Generated by Django 2.0.4 on 2018-10-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20181005_0914'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='delivery',
            table=None,
        ),
    ]
