# Generated by Django 2.0.4 on 2018-04-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180417_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkingsession',
            name='percent_complete',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkingsession',
            name='wps_request',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='checkingsession',
            name='wps_status_location',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
