# Generated by Django 2.0.4 on 2018-07-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_job_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='product_ident',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
