# Generated by Django 2.1.7 on 2019-02-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20181005_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='empty_status_document',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
