# Generated by Django 2.1.7 on 2019-02-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190219_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='last_job_percent',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='last_job_status',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='last_job_uuid',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='product_description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='product_ident',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='size_bytes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
