# Generated by Django 2.0.4 on 2018-07-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_uploadedfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
    ]
