# Generated by Django 2.0.4 on 2018-07-02 07:29

import dashboard.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_uploadedfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='filepath',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='', verbose_name=models.FileField(upload_to=dashboard.models.UploadedFile.user_directory_path)),
            preserve_default=False,
        ),
    ]
