# Generated by Django 2.1.7 on 2019-03-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190221_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='skip_steps',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
