# Generated by Django 2.0.4 on 2018-07-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180702_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='product_ident',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
