# Generated by Django 2.1.7 on 2019-03-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_delivery_skip_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='worker_url',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
