# Generated by Django 2.1.7 on 2019-03-22 17:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_delivery_worker_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('job_status', models.CharField(max_length=64)),
                ('product_ident', models.CharField(max_length=64)),
                ('skip_steps', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('worker_url', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='filepath',
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Delivery'),
        ),
    ]
