# Generated by Django 2.0.4 on 2018-07-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180702_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='file',
        ),
        migrations.AddField(
            model_name='job',
            name='filename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
