# Generated by Django 2.1.7 on 2019-03-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190322_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='last_job_percent',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='last_job_status',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='last_job_uuid',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='skip_steps',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='worker_url',
        ),
        migrations.AddField(
            model_name='job',
            name='product_description',
            field=models.CharField(default='Corine Land Cover', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(default='waiting', max_length=64),
        ),
    ]
