# Generated by Django 2.0.4 on 2018-07-02 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180702_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.UploadedFile'),
        ),
    ]
