# Generated by Django 2.2.27 on 2024-02-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_apiuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200)),
                ('access_key', models.CharField(max_length=100)),
                ('secret_key', models.CharField(max_length=100)),
                ('bucketname', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='s3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.S3Info'),
        ),
    ]
