# Generated by Django 2.2.27 on 2024-02-13 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20240207_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s3info',
            old_name='pattern',
            new_name='key_prefix',
        ),
    ]
