# Generated by Django 2.0.4 on 2018-07-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20180702_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_uuid',
            field=models.CharField(default='a2979641-c973-44d1-9ce9-6345ae22e678', max_length=32),
            preserve_default=False,
        ),
    ]
