# Generated by Django 4.2.25 on 2025-11-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='product_family',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
