# Generated by Django 4.2.25 on 2026-01-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_userprofile_product_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='size_bytes',
            field=models.BigIntegerField(),
        ),
    ]
