# Generated by Django 4.2.25 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_delivery_size_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='aoi_code',
            field=models.CharField(blank=True, db_index=True, default=None, editable=False,
                                   help_text='Canonical AOI code detected in the delivery job result.', max_length=255,
                                   null=True),
        ),
    ]
