# Generated by Django 4.2.25 on 2026-08-21

from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def copy_latest_job_aoi_code(apps, schema_editor):
    Delivery = apps.get_model("dashboard", "Delivery")
    Job = apps.get_model("dashboard", "Job")
    database_alias = schema_editor.connection.alias
    latest_job_aoi_code = (Job.objects.using(database_alias)
                           .filter(delivery_id=OuterRef("pk"))
                           .order_by("-date_created", "-job_uuid")
                           .values("aoi_code")[:1])
    Delivery.objects.using(database_alias).update(aoi_code=Subquery(latest_job_aoi_code))


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_job_aoi_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="aoi_code",
            field=models.CharField(
                blank=True,
                default=None,
                editable=False,
                help_text="Canonical AOI code projected from the latest delivery job.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.RunPython(copy_latest_job_aoi_code, migrations.RunPython.noop),
    ]
