# Generated by Django 5.2.17 on 2026-08-26 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_reconcile_aoi_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySubmission',
            fields=[
                ('submission_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aoi_code', models.CharField(editable=False, max_length=255)),
                ('aoi_code_submitted', models.CharField(editable=False, max_length=255)),
                ('submitted_by_username', models.CharField(max_length=150)),
                ('request_channel', models.CharField(choices=[('browser', 'Browser'), ('api', 'API'), ('legacy', 'Legacy backfill')], max_length=10)),
                ('api_token_name', models.CharField(blank=True, max_length=80)),
                ('publication_state', models.CharField(choices=[('pending', 'Pending'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('review_state', models.CharField(choices=[('accepted', 'Accepted'), ('conflict', 'Conflict'), ('rejected', 'Rejected')], default='accepted', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('publication_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('publication_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('artifact_path', models.CharField(blank=True, max_length=1000)),
                ('artifact_digest', models.CharField(blank=True, max_length=64)),
                ('input_digest', models.CharField(blank=True, max_length=64)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('-requested_at', 'submission_uuid'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('ident',),
            },
        ),
        migrations.CreateModel(
            name='ProductAOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoi_code', models.CharField(max_length=255)),
                ('source_value', models.CharField(blank=True, max_length=255)),
                ('provenance', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('product_release_id', 'aoi_code'),
            },
        ),
        migrations.CreateModel(
            name='ProductRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_key', models.CharField(max_length=100)),
                ('revision', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('catalog_digest', models.CharField(max_length=64)),
                ('coverage_state', models.CharField(choices=[('unknown', 'Coverage unknown'), ('draft', 'Draft coverage'), ('authoritative', 'Authoritative coverage'), ('retired', 'Retired')], default='unknown', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('release_key', '-revision'),
            },
        ),
        migrations.CreateModel(
            name='ProductReleaseDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('product_release_id', '-is_primary', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='QcDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ident', models.CharField(max_length=64)),
                ('digest', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('document', models.JSONField()),
                ('source_path', models.CharField(max_length=500)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('product_ident', '-imported_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='SubmissionConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('opened_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_username', models.CharField(blank=True, max_length=150)),
                ('resolution_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('state', '-opened_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SubmissionConflictEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('opened', 'Opened'), ('reopened', 'Reopened'), ('resolved', 'Resolved')], max_length=10)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('conflict_id', 'version', 'created_at', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='aoi_code_submitted',
            field=models.CharField(blank=True, default=None, editable=False, help_text='Canonical AOI code verified from the ZIP by the latest QC job. ProductAOI.aoi_code is the authoritative expected value.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='content_sha256',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='aoi_code_submitted',
            field=models.CharField(blank=True, default=None, editable=False, help_text='Canonical AOI code verified from the submitted ZIP.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='input_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='qc_tool_version',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name='job',
            name='reference_period',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='request_source',
            field=models.CharField(default='legacy', max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='requested_api_token_id',
            field=models.PositiveBigIntegerField(blank=True, editable=False, help_text='Identifier snapshot of the personal API token used to request the job. It intentionally has no foreign key so deleting a credential cannot rewrite audit history.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requested_api_token_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='job',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_qc_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='requested_by_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='job',
            name='result_metadata',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='result_received_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='result_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['aoi_code_submitted'], name='dash_delivery_zip_aoi_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['content_sha256'], name='dash_delivery_sha_idx'),
        ),
        migrations.AddField(
            model_name='deliverysubmission',
            name='api_token_id',
            field=models.PositiveBigIntegerField(blank=True, editable=False, help_text='Identifier snapshot of the API token used for submission. It is deliberately not a foreign key because credentials may be deleted while submission provenance must remain immutable.', null=True),
        ),
        migrations.AddField(
            model_name='deliverysubmission',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='dashboard.delivery'),
        ),
        migrations.AddField(
            model_name='deliverysubmission',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='dashboard.job'),
        ),
        migrations.AddField(
            model_name='deliverysubmission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('ident', ''), _negated=True), name='dash_product_ident_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='dash_product_name_not_empty'),
        ),
        migrations.AddField(
            model_name='deliverysubmission',
            name='product_aoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='dashboard.productaoi'),
        ),
        migrations.AddField(
            model_name='productrelease',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_product_releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productrelease',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='dashboard.product'),
        ),
        migrations.AddField(
            model_name='productrelease',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='dashboard.productrelease'),
        ),
        migrations.AddField(
            model_name='productaoi',
            name='product_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aois', to='dashboard.productrelease'),
        ),
        migrations.AddField(
            model_name='deliverysubmission',
            name='product_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='dashboard.productrelease'),
        ),
        migrations.AddField(
            model_name='job',
            name='product_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='dashboard.productrelease'),
        ),
        migrations.AddField(
            model_name='productreleasedefinition',
            name='product_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definition_links', to='dashboard.productrelease'),
        ),
        migrations.AddIndex(
            model_name='qcdefinition',
            index=models.Index(fields=['product_ident', '-imported_at'], name='dash_qcdef_ident_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='qcdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('product_ident', ''), _negated=True), name='dash_qcdef_ident_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='qcdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('digest', ''), _negated=True), name='dash_qcdef_digest_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='qcdefinition',
            constraint=models.UniqueConstraint(fields=('product_ident', 'digest'), name='dash_qcdef_ident_digest_uniq'),
        ),
        migrations.AddField(
            model_name='productreleasedefinition',
            name='qc_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_links', to='dashboard.qcdefinition'),
        ),
        migrations.AddField(
            model_name='job',
            name='qc_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='dashboard.qcdefinition'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['aoi_code_submitted'], name='dash_job_zip_aoi_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['delivery', '-date_created', '-job_uuid'], name='dash_job_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_status', 'date_created'], name='dash_job_queue_idx'),
        ),
        migrations.AddField(
            model_name='submissionconflict',
            name='product_aoi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='submission_conflict', to='dashboard.productaoi'),
        ),
        migrations.AddField(
            model_name='submissionconflict',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_submission_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionconflict',
            name='selected_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_for_conflicts', to='dashboard.deliverysubmission'),
        ),
        migrations.AddField(
            model_name='submissionconflictevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_conflict_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionconflictevent',
            name='conflict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='dashboard.submissionconflict'),
        ),
        migrations.AddField(
            model_name='submissionconflictevent',
            name='selected_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conflict_events', to='dashboard.deliverysubmission'),
        ),
        migrations.AddIndex(
            model_name='productrelease',
            index=models.Index(fields=['product', 'coverage_state', 'is_current'], name='dash_release_coverage_idx'),
        ),
        migrations.AddConstraint(
            model_name='productrelease',
            constraint=models.CheckConstraint(condition=models.Q(('release_key', ''), _negated=True), name='dash_release_key_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='productrelease',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gt', 0)), name='dash_release_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='productrelease',
            constraint=models.CheckConstraint(condition=models.Q(('catalog_digest', ''), _negated=True), name='dash_release_digest_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='productrelease',
            constraint=models.UniqueConstraint(fields=('release_key', 'revision'), name='dash_release_key_revision_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productrelease',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('release_key',), name='dash_release_one_current_uniq'),
        ),
        migrations.AddIndex(
            model_name='productaoi',
            index=models.Index(fields=['aoi_code', 'product_release'], name='dash_aoi_code_release_idx'),
        ),
        migrations.AddConstraint(
            model_name='productaoi',
            constraint=models.CheckConstraint(condition=models.Q(('aoi_code', ''), _negated=True), name='dash_product_aoi_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='productaoi',
            constraint=models.UniqueConstraint(fields=('product_release', 'aoi_code'), name='dash_release_aoi_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='deliverysubmission',
            index=models.Index(fields=['product_aoi', 'publication_state', 'review_state'], name='dash_submission_aoi_state_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverysubmission',
            index=models.Index(fields=['product_release', 'publication_state'], name='dash_submission_release_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverysubmission',
            constraint=models.CheckConstraint(condition=models.Q(('aoi_code', ''), _negated=True), name='dash_submission_aoi_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='deliverysubmission',
            constraint=models.CheckConstraint(condition=models.Q(('aoi_code_submitted', ''), _negated=True), name='dash_submission_zip_aoi_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='deliverysubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_state', 'published'), _negated=True), models.Q(('published_at__isnull', False), models.Q(('artifact_path', ''), _negated=True), models.Q(('artifact_digest', ''), _negated=True), models.Q(('input_digest', ''), _negated=True)), _connector='OR'), name='dash_submission_published_complete'),
        ),
        migrations.AddConstraint(
            model_name='productreleasedefinition',
            constraint=models.UniqueConstraint(fields=('product_release', 'qc_definition'), name='dash_release_qcdef_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productreleasedefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product_release',), name='dash_release_primary_def_uniq'),
        ),
        migrations.AddConstraint(
            model_name='submissionconflict',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='dash_conflict_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='submissionconflict',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('selected_submission__isnull', True), ('state', 'open')), models.Q(('resolved_at__isnull', False), ('selected_submission__isnull', False), ('state', 'resolved')), _connector='OR'), name='dash_conflict_state_consistent'),
        ),
        migrations.AddConstraint(
            model_name='submissionconflictevent',
            constraint=models.UniqueConstraint(fields=('conflict', 'version', 'event_type'), name='dash_conflict_event_version_uniq'),
        ),
    ]
