# Generated by Django 5.2.17 on 2026-09-21 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_deliveries', 'Can view deliveries'), ('upload_delivery', 'Can upload deliveries'), ('run_qc', 'Can run quality control'), ('delete_delivery', 'Can delete deliveries'), ('submit_delivery', 'Can submit deliveries'), ('change_password', 'Can change own password'), ('manage_own_account', 'Can manage own account'), ('manage_api_credential', 'Can manage own API credential'), ('manage_configuration', 'Can manage QC Tool configuration'), ('view_product_deliveries', 'Can view deliveries in assigned products'), ('view_product_aggregate_report', 'Can view aggregate reports for assigned products')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PersonalAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('secret_digest', models.CharField(editable=False, max_length=71, unique=True)),
                ('token_hint', models.CharField(blank=True, editable=False, max_length=16)),
                ('permission_snapshot', models.JSONField(default=list, editable=False)),
                ('role_snapshot', models.JSONField(default=list, editable=False)),
                ('product_idents_snapshot', models.JSONField(default=list, editable=False)),
                ('is_administrator_snapshot', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='personal_access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'personal API token',
                'verbose_name_plural': 'personal API tokens',
                'db_table': 'account_api_token',
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='account_token_name_not_empty'), models.UniqueConstraint(fields=('user', 'name'), name='account_token_user_name_uniq')],
            },
        ),
        migrations.CreateModel(
            name='UserProductGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ident', models.CharField(help_text='Canonical business-product identifier or exact QC-definition identifier. A definition assignment does not grant sibling definitions.', max_length=64, verbose_name='Product or QC definition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_product_grant',
                'ordering': ('product_ident', 'pk'),
                'indexes': [models.Index(fields=['product_ident'], name='account_product_ident_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('product_ident', ''), _negated=True), name='account_product_key_not_empty'), models.UniqueConstraint(fields=('user', 'product_ident'), name='account_product_user_key_uniq')],
            },
        ),
    ]
