title: Copernicus Quality Tools
description: Developer, operator, administrator, and user documentation for the CLMS QC Tool

remote_theme: just-the-docs/just-the-docs
search_enabled: true
heading_anchors: true

url: https://eea.github.io
baseurl: /copernicus_quality_tools

aux_links:
  "QC Tool on GitHub":
    - "https://github.com/eea/copernicus_quality_tools"
aux_links_new_tab: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "CLMS QC Tool documentation. Licensed under EUPL-1.2."

plugins:
  - jekyll-sitemap
